# Generated by Django 3.2.16 on 2022-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyNumber',
            fields=[
                ('em_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'emergency_number',
                'managed': False,
            },
        ),
    ]
