# Generated by Django 3.2.16 on 2022-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerRegister',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=50)),
                ('time_info', models.TimeField()),
                ('payment', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'trainer_register',
                'managed': False,
            },
        ),
    ]
