# Generated by Django 3.2.16 on 2022-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('services', models.CharField(max_length=50)),
                ('equipments', models.CharField(max_length=50)),
                ('games', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
    ]
