# Generated by Django 3.2.16 on 2022-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('physical', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_register',
                'managed': False,
            },
        ),
    ]
