# Generated by Django 3.2.16 on 2022-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('camp_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('campname', models.CharField(max_length=50)),
                ('incharge', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'camp',
                'managed': False,
            },
        ),
    ]
