# Generated by Django 3.2.16 on 2022-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_of_item', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
    ]
