# Generated by Django 3.2.16 on 2022-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurfRegister',
            fields=[
                ('turf_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('contactno', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'turf_register',
                'managed': False,
            },
        ),
    ]
