# Generated by Django 3.2.16 on 2022-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('rent_purchase', models.CharField(db_column='rent/purchase', max_length=50)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('rating', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
    ]
