# Generated by Django 3.2.16 on 2022-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('clubname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('email_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'club',
                'managed': False,
            },
        ),
    ]
